from PIL import Image, ImageDraw, ImageFont
import textwrap
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from reportlab.pdfgen import canvas

def add_text_wrapped_to_image(image, text, position, font_path, font_size, text_color=(0, 0, 0), max_width=70):
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(font_path, font_size)
    lines = textwrap.wrap(text, width=max_width)
    y_text = position[1]

    for line in lines:
        width, height = font.getsize(line)
        draw.text(((position[0] - width) / 2, y_text), line, font=font, fill=text_color)
        y_text += height
    return image

def add_name_to_image(name, image):
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype('base\mailings\Poppins-Regular.ttf', 12)
    draw.text((140, 300), name, font=font, fill=(0, 0, 0))
    return image

def add_symptoms_to_image(symptoms, image):
    return add_text_wrapped_to_image(image, symptoms, (275, 370), 'base\mailings\Poppins-Regular.ttf', 12)

def add_diagnosis_to_image(diagnosis, image):
    return add_text_wrapped_to_image(image, diagnosis, (570, 500), 'base\mailings\Poppins-Regular.ttf', 12)

def send_email(receiver_email, subject, message, attachment_path=None, sender_email="praanahealthcarenlp@gmail.com", sender_password="rbhnkxzjwgvwlucr"):
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = subject

    msg.attach(MIMEText(message, 'plain'))

    if attachment_path:
        attach_file(msg, attachment_path)
    print("IM HERE")
    with smtplib.SMTP('smtp.gmail.com', 587) as server:
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())


def attach_file(msg, attachment_path):
    with open(attachment_path, 'rb') as file:
        part = MIMEBase('application', 'octet-stream')
        part.set_payload(file.read())

    encoders.encode_base64(part)

    part.add_header('Content-Disposition', f'attachment; filename="{attachment_path}"')
    msg.attach(part)


def convert_image_to_pdf(image_path, pdf_path):
    img = Image.open(image_path)
    width, height = img.size

    c = canvas.Canvas(pdf_path, pagesize=(width, height))
    c.drawImage(image_path, 0, 0, width, height)
    c.save()

# '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

def  send_prescription(name, symptoms, diagnosis, receiver_email):
    message = "Praana :), This prescription's generated by AI, Do seek practitioners assistance!!"
    
    img = Image.open('base/mailings/template.jpg')

    img = add_name_to_image(name, img)

    img = add_symptoms_to_image(symptoms, img)

    img = add_diagnosis_to_image(diagnosis, img)

    img.save("base\mailings\output.png")

    image_path = 'base\mailings\output.png'
    pdf_path = 'base\mailings\output.pdf'

    convert_image_to_pdf(image_path, pdf_path)

    send_email(receiver_email, "Prescription - from Praana", message, attachment_path='base\mailings\output.pdf')


if __name__ == "__main__":
    
#     img = Image.open('base/mailings/template.jpg')

#     name_text = "Saran Dharshan"
#     img = add_name_to_image(name_text, img)

#     symptoms_text = "HELOOOOO ITS COLD !!"
#     img = add_symptoms_to_image(symptoms_text, img)
    diagnosis_text = """Based on the symptoms you've described, it seems like you have been dealing with chronic sinusitis for the past two years. Sinusitis is an inflammation of the sinus cavities, which can cause symptoms such as nasal congestion, headaches, postnasal drip, fatigue, and facial tenderness.
To help alleviate your symptoms and provide long-lasting relief, I would recommend the following treatment options:
1. Medications: You can try using over-the-counter nasal decongestants, such as pseudoephedrine or oxymetazoline, to relieve nasal congestion. Additionally, saline nasal sprays or rinses can help flush out the sinuses and reduce inflammation. If your symptoms persist, your doctor may prescribe corticosteroids or antibiotics to treat any underlying infection.
2. Lifestyle changes: To manage your sinusitis, it's important to maintain good nasal hygiene. This includes regularly cleaning your nasal passages with saline solution or a neti pot. Avoiding triggers such as allergens or irritants can also help reduce symptoms. In addition, staying hydrated and getting plenty of rest can support your overall immune system.
3. Steam inhalation: Breathing in warm steam can help soothe your nasal passages and relieve congestion. You can do this by taking a hot shower or using a humidifier in your bedroom.
4. Yoga and relaxation techniques: Practicing yoga and relaxation techniques, such as deep breathing exercises or meditation, can help reduce stress and promote overall well-being. This may indirectly alleviate some of your sinusitis symptoms.
It's important to note that these recommendations are general and may vary depending on your specific situation. I would strongly advise you to consult with a healthcare professional, such as an ENT specialist or a primary care physician, who can assess your condition and provide personalized treatment options."""
    # img = add_diagnosis_to_image(diagnosis_text, img)

    # img.save("base\mailings\output.png")

    # receiver_email = 'spsaranthegreat27@gmail.com'
    # subject = 'Test Email'
    # message = 'Hello, this is a test email.'
    # image_path = 'base\mailings\output.png'
    # pdf_path = 'base\mailings\output.pdf'

    # convert_image_to_pdf(image_path, pdf_path)
    # send_email(receiver_email, subject, message, attachment_path='base\mailings\output.pdf')

    # send_email("amritsubramanian.c@gmail.com", "New Article", "Give your eyes exercise... checkout this new article ")
    send_prescription("komakaa", "Sinusitis SinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitisSinusitis", diagnosis_text, "cb.en.u4aie22045@cb.students.amrita.edu")