# Generated by Django 4.2.3 on 2023-12-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
    ]
